[package]
name = "pathtracer"
version = "0.1.0"
authors = ["Alexey Terekhov"]

[lib]
name = "pathtracer"
path = "src/lib.rs"

[dependencies]
nalgebra = "0.10.*"
image = "*"
rand = "*"
scoped_threadpool =  {version = "0.1.*", git = "https://github.com/Kimundi/scoped-threadpool-rs"}