[package]
name = "app"
version = "0.1.0"
authors = ["Alexey Terekhov"]

[lib]
name = "pt_app"

[dependencies]

gfx_core = { git = 'https://github.com/gfx-rs/gfx' }
gfx_device_gl = { git = 'https://github.com/gfx-rs/gfx' }
gfx_window_glutin = { git = 'https://github.com/gfx-rs/gfx' }
gfx = { git = 'https://github.com/gfx-rs/gfx' }

glutin = "*"
genmesh = "*"
image = "*"
nalgebra = "0.10.*"
obj-rs = "*"
pathtracer = {path = "src/pt", version = "*"}
time = "0.1.*"



[[example]]
name = "test"
path = "examples/test/main.rs"

[[example]]
name = "apptest"
path = "examples/apptest/apptest.rs"

[[example]]
name = "spheres"
path = "examples/spheres/spheres.rs"

